proyectoweb/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from proyectoweb import settings
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
    path('agregar_post', views.agregar_post, name='agregar_post'),
    path('editar_post/<int:id>/', views.editar_post, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_post, name='eliminar_post'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/carro/urls.py
from django.urls import path
from . import views
app_name="carro"

urlpatterns =[
    path('carro/', views.carro, name='carro'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

proyectoweb/proyectoweb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('servicios/', include('servicios.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('ProyectoWebApp.urls')),
    #path('accounts/', include('django.contrib.auth.urls')), borrar esta linea
path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'), 
        name='reset_password'),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), 
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), 
        name='password_reset_complete'),

]

proyectoweb/tienda/urls.py
from django.urls import path
from django.conf.urls.static import static
from proyectoweb import settings
from django.conf import settings
from . import views

urlpatterns =[
    path('', views.tienda, name='tienda'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),

    ## CRUD categorias
    path('categorias_producto/', views.categorias_producto, name='categorias_producto'),
    path('agregar_categoria_p/', views.agregar_categoria_p, name='agregar_categoria_p'),
    path('editar_categoria_p/<int:id>/', views.editar_categoria_p, name='editar_categoria_p'),
    path('eliminar_categoria_p/<int:id>/', views.eliminar_categoria_p, name='eliminar_categoria_p'),

    ##CRUD PRODUCTOS
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:id>/', views.editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:id>/', views.eliminar_producto, name='eliminar_producto'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='CategoriaProd'
        verbose_name_plural='CategoriasProd'
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'

    def __str__(self):
        return self.nombre
    

proyectoweb/tienda/forms.py
from dataclasses import field
from django import forms
from . models import Producto, CategoriaProd

class CategoriaProductoForm(forms.ModelForm):
    class Meta:
        model = CategoriaProd
        fields = '__all__'

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

proyectoweb/tienda/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from .models import CategoriaProd, Producto
from django.contrib.auth.decorators import login_required
from . forms import CategoriaProductoForm, ProductoForm
#from carro.context_processor import *

# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    categorias = CategoriaProd.objects.all()
    paginador = Paginator(productos, 6)
    page_number = request.GET.get('page')
    page_obj = paginador.get_page(page_number)
    context  ={'productos': productos, 'categorias': categorias,'productos':page_obj}
    return render(request, "tienda/tienda.html",context)

def categoria(request, categoria_id):
    categoria = CategoriaProd.objects.get(id=categoria_id)
    productos = Producto.objects.filter(categorias=categoria)
    context  ={'productos': productos, 'categoria': categoria}
    return render(request, 'tienda/categoria.html', context) 

def categorias_producto(request):
    categorias_producto = CategoriaProd.objects.all()
    context = {'categorias_producto': categorias_producto}
    return render(request, 'categoria_producto/categorias_p.html', context)

@login_required
def agregar_categoria_p(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = CategoriaProductoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('tienda')
        else:
            form = CategoriaProductoForm()

        context = {'form':form}
        return render(request, 'categoria_producto/agregar_categoria_p.html', context)

@login_required
def editar_categoria_p(request, id):
    if request.user.is_superuser:
        categoria_prod = get_object_or_404(CategoriaProd, pk=id)
        if request.method == 'POST':
            form = CategoriaProductoForm(request.POST, instance=categoria_prod)
            if form.is_valid():
                form.save()
                return redirect('tienda')
        else:
            form = CategoriaProductoForm(instance=categoria_prod)
        
        context = {'form':form}
        return render(request, 'categoria_producto/editar_categoria_p.html', context)

@login_required
def eliminar_categoria_p(request, id):
    if request.user.is_superuser:
        categoria_prod = get_object_or_404(CategoriaProd, pk=id)
        categoria_prod.delete()
        return redirect('tienda')

@login_required
def agregar_producto(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = ProductoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('tienda')
        else:
            form = ProductoForm()

        context = {'form':form}
        return render(request, 'productos/agregar_producto.html', context)

@login_required
def editar_producto(request, id):
    if request.user.is_superuser:
        producto = get_object_or_404(Producto, pk=id)
        if request.method == 'POST':
            form = ProductoForm(request.POST, instance=producto)
            if form.is_valid():
                form.save()
                return redirect('tienda')
        else:
            form = ProductoForm(instance=producto)
        
        context = {'form':form}
        return render(request, 'productos/editar_producto.html', context)

@login_required
def eliminar_producto(request, id):
    if request.user.is_superuser:
        producto = get_object_or_404(Producto, pk=id)
        producto.delete()
        return redirect('tienda')

proyectoweb/tienda/templates/tienda/categoria.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}
<title>{% block titulo %}Tienda{% endblock %}</title>
<div class="container">
    <div class="row"></div>
    {% for producto in productos %}

    <div class="col-md-3">
        <div class="card" style="width: 100%; margin: 5px 5px;">
            <a href="{{producto.imagen.url}}">
                <img src="{{producto.imagen.url}}" width="200" height="300" class="card-img-top">
            </a>
            <div class="card-body" style="text-align: center;">
                <h7 class="card-title">{{producto.nombre}}</h7>
                <p class="card-text">$ {{producto.precio}}</p>
            </div>

            <div class="card-footer text-center">
                <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
</div>

<br>
<div>
    {% include 'tienda/paginador.html' %}
</div>
{% endblock %}

proyectoweb/tienda/templates/tienda/paginador.html
 <!--Pagination-->
 <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if productos.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ productos.previous_page_number }}">Previous</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
      </li>
    {% endif %}

    {% if productos.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ productos.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}

    {% for i in productos.paginator.page_range %}
        {% if productos.number == i %}
            <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{ i }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
        {% elif i > productos.number|add:'-5' and i < productos.number|add:'5' %}
             <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if productos.paginator.num_pages > productos.number|add:'4' %}
       <li class="page-item"><a class="page-link" href="?page={{ productos.number|add:'5' }}">&hellip;</a></li>
    {% endif %}

    {% if productos.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ productos.next_page_number }}">Next</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--end of Pagination-->

proyectoweb/tienda/templates/tienda/tienda.html
{% extends 'ProyectoWebApp/base.html' %}
{% load static %}

{% block content %}

<div>
    {% if user.is_authenticated %}
    {% if user.is_superuser %}
    <a href="{% url 'agregar_producto' %}" class="btn btn-sm btn-success">Agregar Producto</a>
    {% endif %}
    {% endif %}
</div>

<!-- Categorías -->

<div style="float:left ; width: auto; margin-top: 10;">

    <div style="text-align: right;">
        <a href="{% url 'categorias_producto' %}" class="btn btn-info">Categorias</a>
    </div>
    <br>
    {% for categoria in categorias %}
    <ul>
        <a href="{% url 'categoria' categoria.id %}" class="btn"
            style="background-color: black; color: gold; width: 100">{{categoria.nombre}}</a>
    </ul>
    {% endfor %}
</div>


<!-- Productos -->
<div class="container">
    <aside>
        <div class="float-right">

            {% if request.user.is_authenticated %}
            <div style="float:right ; width: auto; margin: 10;" class="contenedorFormulario">
                <p>Ir al Carro</p>
                <a href="{% url 'carro:carro' %}">
                    <img src="{% static 'ProyectoWebApp/img/carrito.jpg' %}" class="card-img-top" width="80" height="80"
                        margin: 10;">
                </a>
                <p>Valor: $ {{importe_total_carro}}</p>
            </div>
            {% else %}

            <div class="alert alert-danger text-center" style="margin-top: 10;">Debes hacer Login</div>

            {% endif %}

        </div>

    </aside>

    <div class="row">
        {% for producto in productos %}

        <div class="col-md-4">
            <div class="card" style="width: 100%; margin: 10px 10px 10px 10px;">
                <img src="{{producto.imagen.url}}" class="card-img-top" width="100" height="200">

                <div class="card-body" style="text-align: center;">

                    <h7 class="card-tittle">{{producto.nombre}}</h7>
                    <p class="card-text">$ {{producto.precio}}</p>

                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
                </div>

                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <div class="card-footer text-center">
                    <a href="{% url 'editar_producto' producto.id %}" class="btn btn-info">Editar</a>
                    <a href="{% url 'eliminar_producto' producto.id %}" class="btn btn-danger">Eliminar</a>
                </div>
                {% endif %}
                {% endif %}
            </div>
            <!---card que se cierra-->
        </div>

        {% endfor %}
    </div>
</div>
<br>
<div>
    {% include 'tienda/paginador.html' %}
</div>
{% endblock %}