proyectoweb/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from proyectoweb import settings
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
    path('agregar_post', views.agregar_post, name='agregar_post'),
    path('editar_post/<int:id>/', views.editar_post, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_post, name='eliminar_post'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/carro/urls.py
from django.urls import path
from . import views
app_name="carro"

urlpatterns =[
    path('carro/', views.carro, name='carro'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

proyectoweb/proyectoweb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('servicios/', include('servicios.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('ProyectoWebApp.urls')),
    #path('accounts/', include('django.contrib.auth.urls')), borrar esta linea
path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'), 
        name='reset_password'),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), 
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), 
        name='password_reset_complete'),

]

proyectoweb/carro/models.py
from django.db import models

# Create your models here.

proyectoweb/carro/views.py
from django.shortcuts import render, redirect
from . carro import Carro
from tienda.models import Producto

# Create your views here.

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("tienda")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("carro:carro")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("carro:carro")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("tienda")

def carro(request):
    return render(request, 'carro/carro.html')

proyectoweb/carro/templates/carro/carro.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
<div class=" container">
    <div class="contenedorFormulario">
        <table class="table table-bordered" style="color: white;">
            <thead>

                <tr>
                    <th colspan="3" class="text-center">
                        Carro compras
                    </th>
                </tr>
                <tr>
                    <th colspan="3" class="text-center">
                        <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-danger">Limpiar Carro</a>
                    </th>
                </tr>
                <tr>

                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Suma</th>

                </tr>
            </thead>
            <tbody>
                {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-danger">-</a>
                        <br />

                        $ {{value.precio}}

                    </td>
                </tr>
                {% endfor %}
                {% else %}

                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center">
                            No Hay Productos
                        </div>
                    </td>
                </tr>

                {% endif %}
            </tbody>

            <tfoot>
                <tr>
                    <td colspan="3">

                        Total:$ {{importe_total_carro}}

                    </td>
                </tr>

                {% if request.session.carro.items %}
                <tr>
                    <td colspan="3" style="text-align: center;">
                        <a href="{% url 'procesar_pedido' %}" class="btn btn-success">Pedido</a>
                    </td>
                </tr>
                {% endif %}

            </tfoot>

        </table>
    </div>
</div>
{% else %}

<div class="alert alert-danger text-center">Login</div>

{% endif %}
{% endblock %}