proyectoweb/ProyectoWebApp/urls.py
from django.urls import path
from ProyectoWebApp import views
from django.conf import settings
from django.conf.urls.static import static

from proyectoweb.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns =[
    path('', views.home, name='home'),
    
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from proyectoweb import settings
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
    path('agregar_post', views.agregar_post, name='agregar_post'),
    path('editar_post/<int:id>/', views.editar_post, name='editar_post'),
    path('eliminar_post/<int:id>/', views.eliminar_post, name='eliminar_post'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/proyectoweb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include('autenticacion.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('servicios/', include('servicios.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('ProyectoWebApp.urls')),
    #path('accounts/', include('django.contrib.auth.urls')), borrar esta linea
path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'), 
        name='reset_password'),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), 
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), 
        name='password_reset_complete'),

]

proyectoweb/ProyectoWebApp/models.py
from django.db import models

# Create your models here.

proyectoweb/ProyectoWebApp/views.py
from django.shortcuts import render, HttpResponse
from carro.carro import Carro

# Create your views here.

def home(request):
    carro=Carro(request)
    return render(request, "ProyectoWebApp/home.html")

proyectoweb/ProyectoWebApp/templates/ProyectoWebApp/base.html
<html>

<head>

  {% load static %}

  <!-- Bootstrap -->
  <link href="{% static 'ProyectoWebApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Fonts -->

  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">


  <!-- Styles -->
  <link href="{% static 'ProyectoWebApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

  <h1 class="site-heading text-center text-gold d-none d-lg-block" >

    <span class="site-heading-lower">Gestión de Pedidos</span>
  </h1>

  <div style="color: #EABE3F; text-align: right; margin-right: 100px;">

    {% if user.is_authenticated %}

    Hola {{request.user}} &nbsp;&nbsp;
    <button type="button" class="btn btn-default">
      <a href="{% url 'cerrar_sesion' %} ">Cerrar Sesión</a>
    </button>
    &nbsp;&nbsp;
    <button type="button" class="btn btn-default">
      <a href="{% url 'editar_perfil' %}">Editar Perfil</a>
    </button>

    {% else %}
    No estas logueado<br>
    <button type="button" class="btn btn-default">
      <a href="{% url 'loguear' %}">Login</a>
    </button>
    &nbsp;&nbsp;
    <button type="button" class="btn btn-default">
      <a href="{% url 'autenticacion' %}">Regístrate</a>
    </button>
    {% endif %}

  </div>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home' %}">Gestión de
        Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/servicios/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'servicios' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/tienda/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contacto/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'contacto' %}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path|slice:':6' == '/blog/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:blog' %}">Blog</a>
          </li>
          <li class="nav-item {% if request.path == '/pedidos/lista_pedidos/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'lista_pedidos' %}">Pedidos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <!-- Contenido Cambiante -->
  {% block content %}

  {% endblock %}

  <!-- Footer -->
  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
          </span>
        </a>

          <a href="https://www.facebook.com/" class="link">
            <img src="{% static 'ProyectoWebApp/img/facebook.jpg' %}" alt="" style="width:50px">
          </a>
          <a href="https://www.instagram.com/" class="link">
            <img src="{% static 'ProyectoWebApp/img/instagram.jpg' %}" alt="" style="width:50px">
          </a>
          <a href="https://www.whatsapp.com/" class="link">
            <img src="{% static 'ProyectoWebApp/img/whatsapp.jpg' %}" alt="" style="width:50px">
          </a>

      </p>
      <p class="m-0 mbt">
        <a href="sample.html" class="link">Política de privacidad</a> ·
        <a href="sample.html" class="link">Aviso legal</a> ·
        <a href="sample.html" class="link">Cookies</a>
      </p>
      <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
    </div>
  </footer>

  <!-- Bootstrap -->
  <script src="{% static 'ProyectoWebApp/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'ProyectoWebApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

proyectoweb/ProyectoWebApp/templates/ProyectoWebApp/home.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>

 
  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}